import { GradientMap, Preset } from './types';

export const VINTAGE_GRADIENT_MAPS: GradientMap[] = [
  // Inspirados diretamente nas imagens enviadas pelo usuário
  {
    id: 'rose_moss',
    name: 'Rosa & Musgo Vintage',
    category: 'duotone',
    colors: ['#28422A', '#E890A2'],
    previewCss: 'linear-gradient(135deg, #28422A 0%, #E890A2 100%)',
  },
  {
    id: 'mustard_navy',
    name: 'Mostarda & Azul Marinho',
    category: 'duotone',
    colors: ['#0B1B32', '#F1B838'],
    previewCss: 'linear-gradient(135deg, #0B1B32 0%, #F1B838 100%)',
  },
  {
    id: 'riso_coral_indigo',
    name: 'Riso Coral & Índigo Noturno',
    category: 'tritone',
    colors: ['#0A1329', '#E04F43', '#F9EAD3'],
    previewCss: 'linear-gradient(135deg, #0A1329 0%, #E04F43 50%, #F9EAD3 100%)',
  },
  {
    id: 'lilac_charcoal',
    name: 'Lilás Retrô & Carvão',
    category: 'duotone',
    colors: ['#1A1720', '#C4B7DC'],
    previewCss: 'linear-gradient(135deg, #1A1720 0%, #C4B7DC 100%)',
  },
  {
    id: 'classic_fanzine_bw',
    name: 'Fanzine Monocromático',
    category: 'monochrome',
    colors: ['#111111', '#E8E5DD'],
    previewCss: 'linear-gradient(135deg, #111111 0%, #E8E5DD 100%)',
  },
  {
    id: 'kraft_paper_sepia',
    name: 'Papel Kraft & Sépia',
    category: 'duotone',
    colors: ['#2B1B10', '#E4C9A0'],
    previewCss: 'linear-gradient(135deg, #2B1B10 0%, #E4C9A0 100%)',
  },
  {
    id: 'tangerine_teal',
    name: 'Tangerina & Azul Petróleo',
    category: 'duotone',
    colors: ['#0A2A33', '#EB683F'],
    previewCss: 'linear-gradient(135deg, #0A2A33 0%, #EB683F 100%)',
  },
  {
    id: 'cyanotype_blueprint',
    name: 'Cianótipo & Marfim',
    category: 'duotone',
    colors: ['#00264D', '#F4F0E4'],
    previewCss: 'linear-gradient(135deg, #00264D 0%, #F4F0E4 100%)',
  },
  {
    id: 'acid_lemon_prussian',
    name: 'Limão Ácido & Azul Prussiano',
    category: 'duotone',
    colors: ['#0F243E', '#D9EA49'],
    previewCss: 'linear-gradient(135deg, #0F243E 0%, #D9EA49 100%)',
  },
  {
    id: 'retro_pulp_fiction',
    name: 'Pulp Fiction dos Anos 50',
    category: 'tritone',
    colors: ['#1C1014', '#BA2D29', '#F1DAA2'],
    previewCss: 'linear-gradient(135deg, #1C1014 0%, #BA2D29 45%, #F1DAA2 100%)',
  },
  {
    id: 'sakura_forest',
    name: 'Sakura & Floresta',
    category: 'duotone',
    colors: ['#183424', '#F4BAC5'],
    previewCss: 'linear-gradient(135deg, #183424 0%, #F4BAC5 100%)',
  },
  {
    id: 'bubblegum_cyber_80s',
    name: 'Chiclete 80s & Menta',
    category: 'duotone',
    colors: ['#182B33', '#F75C8F'],
    previewCss: 'linear-gradient(135deg, #182B33 0%, #F75C8F 100%)',
  },
  {
    id: 'terracotta_cobalt',
    name: 'Terracota & Azul Cobalto',
    category: 'tritone',
    colors: ['#121E47', '#C85C32', '#F7E7CE'],
    previewCss: 'linear-gradient(135deg, #121E47 0%, #C85C32 50%, #F7E7CE 100%)',
  },
  {
    id: 'woodblock_vermilion',
    name: 'Xilogravura Vermelha & Tinta Sumi',
    category: 'tritone',
    colors: ['#141416', '#C7362E', '#F6E5C9'],
    previewCss: 'linear-gradient(135deg, #141416 0%, #C7362E 50%, #F6E5C9 100%)',
  },
  {
    id: 'emerald_riso_cream',
    name: 'Esmeralda Riso & Creme',
    category: 'duotone',
    colors: ['#0A3728', '#FFF3D4'],
    previewCss: 'linear-gradient(135deg, #0A3728 0%, #FFF3D4 100%)',
  },
  {
    id: 'sunflower_plum',
    name: 'Girassol 70s & Ameixa',
    category: 'duotone',
    colors: ['#310D20', '#E5A93B'],
    previewCss: 'linear-gradient(135deg, #310D20 0%, #E5A93B 100%)',
  },
  {
    id: 'neo_noir_red',
    name: 'Neo Noir Carmesim',
    category: 'duotone',
    colors: ['#0A0608', '#D41E38'],
    previewCss: 'linear-gradient(135deg, #0A0608 0%, #D41E38 100%)',
  },
  {
    id: 'electric_copper',
    name: 'Cobre Envelhecido & Turquesa',
    category: 'tritone',
    colors: ['#09262B', '#C96E42', '#EAE6D6'],
    previewCss: 'linear-gradient(135deg, #09262B 0%, #C96E42 50%, #EAE6D6 100%)',
  },
  {
    id: 'lavender_olive',
    name: 'Lavanda & Oliva Pálida',
    category: 'duotone',
    colors: ['#282A1C', '#D8CEE8'],
    previewCss: 'linear-gradient(135deg, #282A1C 0%, #D8CEE8 100%)',
  },
  {
    id: 'amber_terminal',
    name: 'Fósforo Âmbar & Preto',
    category: 'monochrome',
    colors: ['#110E08', '#FFB224'],
    previewCss: 'linear-gradient(135deg, #110E08 0%, #FFB224 100%)',
  },
  {
    id: 'french_paper_warm_grey',
    name: 'Cinza Tipográfico Quente',
    category: 'monochrome',
    colors: ['#1C1B1A', '#DFDCD4'],
    previewCss: 'linear-gradient(135deg, #1C1B1A 0%, #DFDCD4 100%)',
  }
];

export const PRESETS: Preset[] = [
  {
    id: 'wavy_engraving_studio',
    name: 'Gravura em Linhas Onduladas',
    subtitle: 'Woodcut & Currency Lines',
    description: 'Linhas contínuas sinusoidais de xilogravura clássica e gravura de cédulas com espessura variável.',
    badge: 'Popular',
    params: {
      patternType: 'wavy_engraving',
      frequency: 72,
      angle: 15,
      contrast: 1.35,
      threshold: 0.48,
      inkBleed: 0.18,
      misregistration: 0.0,
      paperGrain: 0.32,
      xeroxGrit: 0.15,
      waveFrequency: 2.4,
      waveAmplitude: 0.45,
      colorMode: 'gradient_map',
      gradientMapId: 'lilac_charcoal',
      customColors: {
        shadow: '#1A1720',
        highlight: '#C4B7DC',
      },
      invert: false,
    },
  },
  {
    id: 'risograph_drum_print',
    name: 'Risografia & Silkscreen',
    subtitle: 'Offset Plates & Misregistration',
    description: 'Separação de matrizes com deslocamento de cor, textura orgânica de tinta e base quente de papel.',
    badge: 'Destaque',
    params: {
      patternType: 'risograph_stipple',
      frequency: 90,
      angle: 45,
      contrast: 1.25,
      threshold: 0.5,
      inkBleed: 0.35,
      misregistration: 2.8,
      paperGrain: 0.55,
      xeroxGrit: 0.22,
      waveFrequency: 1.0,
      waveAmplitude: 0.0,
      colorMode: 'gradient_map',
      gradientMapId: 'riso_coral_indigo',
      customColors: {
        shadow: '#0A1329',
        midtone: '#E04F43',
        highlight: '#F9EAD3',
      },
      invert: false,
    },
  },
  {
    id: 'classic_halftone_dots',
    name: 'Halftone Reticulado Clássico',
    subtitle: 'Vintage Screenprint 45°',
    description: 'Reticulado vintage de pontos esféricos com gradiente de alta fidelidade e toque editorial.',
    params: {
      patternType: 'halftone_dots',
      frequency: 64,
      angle: 45,
      contrast: 1.3,
      threshold: 0.52,
      inkBleed: 0.22,
      misregistration: 0.0,
      paperGrain: 0.3,
      xeroxGrit: 0.1,
      waveFrequency: 0.0,
      waveAmplitude: 0.0,
      colorMode: 'gradient_map',
      gradientMapId: 'rose_moss',
      customColors: {
        shadow: '#28422A',
        highlight: '#E890A2',
      },
      invert: false,
    },
  },
  {
    id: 'xerox_grunge_fanzine',
    name: 'Xerox Fanzine & Toner Grit',
    subtitle: 'Photocopy Distress & Dust',
    description: 'Alto contraste analógico, grão de toner em pó, poeira de fotocopiadora e fibra de celulose áspera.',
    params: {
      patternType: 'xerox_grunge',
      frequency: 110,
      angle: 0,
      contrast: 1.6,
      threshold: 0.45,
      inkBleed: 0.4,
      misregistration: 1.2,
      paperGrain: 0.65,
      xeroxGrit: 0.7,
      waveFrequency: 1.5,
      waveAmplitude: 0.1,
      colorMode: 'gradient_map',
      gradientMapId: 'classic_fanzine_bw',
      customColors: {
        shadow: '#111111',
        highlight: '#E8E5DD',
      },
      invert: false,
    },
  },
  {
    id: 'comic_book_cmyk',
    name: 'Quadrinhos Roseta CMYK',
    subtitle: '1960s Newsprint Press',
    description: 'Impressão industrial de quadrinhos clássicos com roseta de quatro canais e cores vibrantes preservadas.',
    params: {
      patternType: 'cmyk_rosette',
      frequency: 58,
      angle: 45,
      contrast: 1.2,
      threshold: 0.5,
      inkBleed: 0.28,
      misregistration: 2.2,
      paperGrain: 0.42,
      xeroxGrit: 0.18,
      waveFrequency: 0.0,
      waveAmplitude: 0.0,
      colorMode: 'original_cmyk',
      gradientMapId: 'retro_pulp_fiction',
      customColors: {
        shadow: '#1C1014',
        midtone: '#BA2D29',
        highlight: '#F1DAA2',
      },
      invert: false,
    },
  },
  {
    id: 'concentric_optical_lines',
    name: 'Gravura Concéntrica Óptica',
    subtitle: 'Radial Engraved Ripple',
    description: 'Linhas concêntricas que fluem do centro da imagem criando profundidade óptica e dinamismo.',
    params: {
      patternType: 'concentric_waves',
      frequency: 60,
      angle: 0,
      contrast: 1.3,
      threshold: 0.48,
      inkBleed: 0.15,
      misregistration: 0.0,
      paperGrain: 0.28,
      xeroxGrit: 0.12,
      waveFrequency: 3.0,
      waveAmplitude: 0.35,
      colorMode: 'gradient_map',
      gradientMapId: 'acid_lemon_prussian',
      customColors: {
        shadow: '#0F243E',
        highlight: '#D9EA49',
      },
      invert: false,
    },
  },
  {
    id: 'vintage_crosshatch',
    name: 'Hachura Cruzada & Bico de Pena',
    subtitle: 'Pen & Ink Crosshatch',
    description: 'Malha dupla de linhas em ângulos complementares simulando desenho tradicional em bico de pena.',
    params: {
      patternType: 'crosshatch',
      frequency: 68,
      angle: 45,
      contrast: 1.4,
      threshold: 0.5,
      inkBleed: 0.2,
      misregistration: 0.0,
      paperGrain: 0.45,
      xeroxGrit: 0.2,
      waveFrequency: 0.0,
      waveAmplitude: 0.0,
      colorMode: 'gradient_map',
      gradientMapId: 'kraft_paper_sepia',
      customColors: {
        shadow: '#2B1B10',
        highlight: '#E4C9A0',
      },
      invert: false,
    },
  },
  {
    id: 'pop_art_screenprint',
    name: 'Pop Art Mostarda & Índigo',
    subtitle: 'Bold Poster Screenprint',
    description: 'Estilo de cartaz pop dos anos 60 com alto impacto visual, sombras densas e realce quente.',
    params: {
      patternType: 'halftone_dots',
      frequency: 50,
      angle: 30,
      contrast: 1.45,
      threshold: 0.54,
      inkBleed: 0.3,
      misregistration: 1.8,
      paperGrain: 0.4,
      xeroxGrit: 0.15,
      waveFrequency: 0.0,
      waveAmplitude: 0.0,
      colorMode: 'gradient_map',
      gradientMapId: 'mustard_navy',
      customColors: {
        shadow: '#0B1B32',
        highlight: '#F1B838',
      },
      invert: false,
    },
  },
];
